config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	resources :plays

	root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
	belongs_to :user
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
	has_many :plays
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
	before_action :find_play, only: [:show, :edit, :update, :destroy ] 

	def index
		@plays = Play.all.order("created_at DESC")
	end

	def new
		@play = current_user.plays.build
		@categories = Category.all.map{ |c| [c.name, c.id]}
	end

	def show
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id]}
		
	end

	def update
		@play.category_id = params[:category_id]
	
		
	
		if @play.update(play_params)
			redirect_to play_path(@play)
		else
			render 'edit'
		end
	end

	def destroy
		@play.destroy
		redirect_to root_path
	end


	def create
		@play = current_user.play.build(play_params)
		@play.category_id = params[:category_id]

		if @play.save
			redirect_to root_path
		else
			render 'new'
		end 
	end

	private

	def play_params
		params.require(:play).permit(:title, :description, :director, :category_id)
	end

	def find_play
		@play = Play.find(params[:id])	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadway</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <div class="container">
        <%= yield %>
       </div>

  </body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), prompt_text => "Select Category") %>
  <%= f.input :title, label: 'Play title' %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1>Edit</h1>

<%= render 'form'%>

app/views/plays/index.html.erb
		
<% @plays.each do |play| %>
	<%= link_to play.title, play_path(play)%>
<% end -%>


<%= link_to "New Play", new_play_path %>

app/views/plays/new.html.erb
<h1>New</h1>

<%= render 'form'%>

app/views/plays/show.html.erb
		
<h2><%= @play.title %> </h2>
<h2><%= @play.director %></h2>
<p><%= @play.description %></p>


<div class="links btn-group">
	<% if user_signed_in? %>
		<% if @play.user_id == current_id %>	
			<%= link_to "New Play", new_play_path %>
			<%= link_to "Back", root_path %>
			<%= link_to "Edit", edit_play_path(@play) %>
			<%= link_to "Delete", play_path(@play), method: :delete, data: { confirm: "Are you sure?"} %>
		<% end -%>
	<% end -%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Brand', root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in?%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% else %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Edit',  edit_user_registration_path %></li>
        <% end -%>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
          
          
          
          </ul>
        </li>
      </ul>
      <% if user_signed_in?%>
          <%= link_to "New Play", new_play_path, class: "navbar-brand" %>
          <% end -%>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>